use_frameworks!

platform :ios, '9.0'

target 'SYCharmJunkie_Example' do
  pod 'SYCharmJunkie', :path => '../'

  target 'SYCharmJunkie_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
